# Site settings
title: Kris Mannino 
email: KrisMannino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kris Mannino's Blog for Nashville Software School Cohort 7.
  

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: '@krismunny' 
github_username: 'krismannino'

# Build settings
markdown: kramdown
